apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aap-basics-demo
  title: aap-basics-demo
  description: Ansible Automation Platform hands-on demo showcasing core capabilities
  annotations:
    ph.rhdp.io/content-type: demo
    ph.rhdp.io/deployment-mode: rhdp_published
    ph.rhdp.io/github-user: treddy
    ph.rhdp.io/owner: treddy@redhat.com
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhpds/aap-basics-demo
  tags:
  - publishing-house
  - demo
  - rhdp-published
  links:
  - url: https://github.com/rhpds/aap-basics-demo
    title: Repository
    icon: github
  - url: https://devspaces.apps.ocpv-infra01.dal12.infra.demo.redhat.com#https://github.com/rhpds/aap-basics-demo
    title: Open in DevSpaces
    icon: catalog
  - url: https://central-api-publishing-house.apps.ocpv-infra01.dal12.infra.demo.redhat.com
    title: Central
    icon: dashboard
  - url: https://redhat.atlassian.net/browse/RHDPCD-1840
    title: Jira Epic
    icon: bugs
spec:
  type: content
  lifecycle: experimental
  owner: rhdp-team
  system: publishing-house
