site_name: AAP Basics Demo
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Introduction To Aap: modules/module-01-introduction-to-aap.md
  - Module 2 - Creating Playbooks: modules/module-02-creating-playbooks.md
  - Module 3 - Job Templates: modules/module-03-job-templates.md
plugins:
- techdocs-core
